### PR TITLE
[Fix kbss-cvut/fta-fmea-ui#47] Assign failure mode to component

### PR DESCRIPTION
**Pull request by Matthew-Kulich**

### CODE REVIEW

**Comment by kostobog** [comment]
Seams ok.

**Comment by kostobog** [comment]
The bidirectional relationship between component and failure mode is corrupted. I added hasFailureMode relation between components and failure modes where it was missing. Here is the used SPARQL query:

```
PREFIX app: <http://onto.fel.cvut.cz/ontologies/fta-fmea-application/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

DELETE {} 
INSERT {
    GRAPH <http://onto.fel.cvut.cz/ontologies/fta-fmea-application/data-issue-fix-001>{
    	?c app:hasFailureMode ?fm.
	}
}WHERE{
    ?fm app:hasName ?name;
        a app:FailureMode;
        app:hasComponent ?c.
    OPTIONAL{
        ?c app:hasName ?cname; 
    }
    FILTER NOT EXISTS{
        ?c app:hasFailureMode ?fm
    }
}
```

**Comment by Matthew-Kulich** [comment]
It was related to the old implementation or is it even relevant to this fix ? @kostobog

**Comment by kostobog** [comment]
I though it is kind of relevant as it fixes the missing relation _hasFailureMode_ which is the subject of this fix in the source code of this pull request. However, I can move it to separate issue if you don't see at as related.

**Comment by Matthew-Kulich** [comment]
I meant if the bidirectional relationship is still corrupted after the fix, but you only inserted manual solution.My bad, I understood it badly,sorry for confusion.

Yes, it certainly is related to this.

**Pull request merged**
